name: WordPress Plugin CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [7.2, 7.4, 8.0]
        wp-versions: [5.0, 6.0, 6.4]

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, zip
        tools: composer

    - name: Validate composer.json and composer.lock
      if: hashFiles('composer.json')
      run: composer validate --strict

    - name: Install dependencies
      if: hashFiles('composer.json')
      run: composer install --prefer-dist --no-progress

    - name: PHP Lint
      run: find . -type f -name '*.php' -print0 | xargs -0 -n1 php -l

    - name: Create WordPress test environment
      run: |
        mkdir -p /tmp/wordpress-tests-lib
        svn co --quiet https://develop.svn.wordpress.org/tags/${{ matrix.wp-versions }}/tests/phpunit/includes/ /tmp/wordpress-tests-lib/includes
